name: iris_api
description: Dart client for Iris API
version: 1.0.0
homepage: https://github.com/c0dwiz/IrisAPI-dart
repository: https://github.com/c0dwiz/IrisAPI-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0